### ISSUE TITLE
Delete(T entity) throw an excption

### ISSUE THREAD

**Issue by emiliano84** [threenine/Threenine.Data#1]
_dbSet.Find(entity); throw the follow exception because expect to receive the primary key as parameter and not the entity

> {System.ArgumentException: The key value at position 0 of the call to 'DbSet<Category>.Find' was of type 'Category', which does not match the property type of 'int'.
>    at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindTracked(Object[] keyValues, IReadOnlyList`1& keyProperties)
>    at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.Find(Object[] keyValues)
>    at Common.Data.Repository.Repository`1.Delete(T entity)
>    at Common.Data.Service.BaseService`1.Delete(T entity)}

```
 public void Delete(T entity)
        {
            T existing = _dbSet.Find(entity);
            if (existing != null) _dbSet.Remove(existing);
        }
```

I wrote this method to retrieve the primary key from the entity

```
        public int GetKey(T entity)
        {
            var keyName = DbContext.Model.FindEntityType(typeof(T)).FindPrimaryKey().Properties
                .Select(x => x.Name).Single();

            return (int)entity.GetType().GetProperty(keyName).GetValue(entity, null);
        }
```

**Comment by garywoodfine** [comment]
I will patch this over the weekend. Should be fairly easy enough to fix. 
Thanks for raising the issue

**Comment by garywoodfine** [comment]
Just checked in an update and deployed updated version to nuget.   There have been some addtional methods added for delete, which should now cater for most needs.
