### ISSUE TITLE
Readonly repository

### ISSUE THREAD

**Issue by EvilLord666** [threenine/Threenine.Data#10]
I think it would be greate to have version of Repository that uses DB in read-only mode.

**Comment by garywoodfine** [comment]
I could create a ReadOnly interface.  Cool idea, I'll try get round to it this week

**Comment by garywoodfine** [comment]
Added a readonly repository interface with implementation,  Also added some additional unit tests.
Also upgrdaded the library to make use of .net core 2.1 and EF Framework versions.
