### ISSUE TITLE
Provide example of Create, Update, Delete Api Examples.

### ISSUE THREAD

**Issue by maylortaylor** [threenine/Threenine.Data#17]
Currently there is only one Api in use (`PersonsController > Get()`). 
I would love to see more examples of how to add one, add many, update one, update many, delete one, delete many, etc.

**Comment by garywoodfine** [comment]
I'll try add some examples

**Comment by murattdogan** [comment]
what is time some examples

**Comment by garywoodfine** [comment]
Unfortunately I have a lot of work on at the moment, and just don't have much time to dedicate to this at this stage
