### ISSUE TITLE
provide sample for Projection & Including

### ISSUE THREAD

**Issue by tamilselvanid** [threenine/Threenine.Data#18]
Using getLIst() method

**Comment by tamilselvanid** [comment]
var enquiries = _unitOfWork.GetRepository<Enquiry>().GetList().Items;
        
       
            foreach(Enquiry enquiry in enquiries)
            {
                Enquiries e = new Enquiries();
                e.Identifier = enquiry.Identifier;
                e.Created = enquiry.Created;
                e.Contact = _unitOfWork.GetRepository<Contact>().GetList(predicate: x => x.Id == enquiry.ContactId).Items.FirstOrDefault();
                e.Status = _unitOfWork.GetRepository<EnquiryStatus>().GetList().Items.Where(predicate: x => x.Id == enquiry.StatusId).FirstOrDefault();
                e.EnquiryType = _unitOfWork.GetRepository<EnquiryType>().GetList().Items.Where(predicate: x => x.Id == enquiry.EnquiryTypeId).FirstOrDefault();
                e.EnquiryProducts = _unitOfWork.GetRepository<EnquiryProduct>().GetList().Items.Where(predicate: x => x.EnquiryId == enquiry.Id).FirstOrDefault();
                if(e.EnquiryProducts!=null)
                e.EnquiryProducts.Product= _unitOfWork.GetRepository<Product>().GetList().Items.Where(predicate: x => x.Id ==e.EnquiryProducts.ProductId).FirstOrDefault();
                lst.Add(e);
            }

**Comment by tamilselvanid** [comment]
enquiries contain of contact ,enquirystatus I try to use include but

![image](https://user-images.githubusercontent.com/8722886/48317494-31455b80-e619-11e8-881d-4f9b4c525cd5.png)

**Comment by garywoodfine** [comment]
Thanks , just trying to find some time to update the documentation and add some additional functionality.  I am currently very busy on another project. Hopefully I can find sometime in a couple of days
