### ISSUE TITLE
Get All Items

### ISSUE THREAD

**Issue by uchetfield** [threenine/Threenine.Data#20]
Since all the Get() method is marked as obsolete what is the best method to return all of the items from a table?  If the scenario is to pull all of the records from a lookup table that may have 30 items or more but not so many that it would require paging it seems awkward to pass in Int32.Max as the  size parameter and the have IPaginate object as the result when I'm just looking for a collection of objects.

**Comment by kalkotekedar** [comment]
I am facing the same issue with, Is there any way to get all the records?
