### ISSUE TITLE
Use GetRepository and GetRepositoryAsync at same service throughs an exception

### ISSUE THREAD

**Issue by ahmdsamir91** [threenine/Threenine.Data#32]
## Description

using both in the same method 

```
repository = _unitOfWork.GetRepository<User>();
 repositoryAync = _unitOfWork.GetRepositoryAsync<User>();
```

throws an exception
System.InvalidCastException: 'Unable to cast object of type 'Threenine.Data.Repository`1[User]' to type 'Threenine.Data.IRepositoryAsync`1[User]'.'

I think if we keep separate dictionaries in uow for each repo type could fix the issue.

**Comment by garywoodfine** [comment]
Feel free to raise a Pull Request with a proposed solution.

**Comment by garywoodfine** [comment]
You probably don't wan to doing what you're trying to do.  

Something like this is how you would do Async updates, by using the CommitAsync method

```csharp
         public async Task UpdateUserName(string newName, int userId)
{
           
          
            var user =  uow.GetRepository<User>().SingleOrDefault(x => x.Id == userId);;

        
            user.Name = newName;
           
           uow.GetRepository<User>().Update(user);

       return     await uow.CommitAsync();
}
```

**Comment by garywoodfine** [comment]
I have just added an update to enable adding multiple repository types to the dictionary.
Maybe check that out to see if that works for you.
